#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  sync-external-impeccable.sh --source-repo <path> [--dest <dir>]

Copies the Codex bundle generated by an impeccable fork into this repository's
external bundle area.

Expected source path inside the fork:
  dist/agents/.agents/skills/impeccable
EOF
}

SOURCE_REPO=""
DEST="$REPO_ROOT/external/impeccable/codex/impeccable"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source-repo)
      SOURCE_REPO="${2:-}"
      shift 2
      ;;
    --dest)
      DEST="${2:-}"
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$SOURCE_REPO" ]]; then
  usage >&2
  exit 1
fi

SOURCE_DIR="$SOURCE_REPO/dist/agents/.agents/skills/impeccable"

if [[ ! -d "$SOURCE_DIR" ]]; then
  echo "Source bundle not found: $SOURCE_DIR" >&2
  exit 1
fi

mkdir -p "$(dirname "$DEST")"
rm -rf "$DEST"
cp -R "$SOURCE_DIR" "$DEST"

echo "Synced impeccable bundle to $DEST"
